substitutions:
  _REGION: asia-northeast1
  _REPO: comfy

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [ 'build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/comfyui:$COMMIT_SHA', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [ 'tag', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/comfyui:$COMMIT_SHA', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/comfyui:prod' ]

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/comfyui:$COMMIT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/comfyui:prod'

options:
  logging: CLOUD_LOGGING_ONLY


